### ISSUE TITLE
`require('csv2md')` does not work

### ISSUE THREAD

**Issue by tukusejssirs** [pstaender/csv2md#13]
Note: I am fairly new Node.js and whole JavaScript.

---

I’d like to use your module synchronously in a Node.js script (`.js`), therefore I can’t simply `import` your module.

I tried to use `csv2md = require('csv2md')`, but `csv2md` is an empty object (`{}`) and Node.js throws the following error: `TypeError: csv2md is not a function`.

Could you please tell me why does it not work?

Thanks in advance!

---

**Update:** I have installed `csv2md` globally using `sudo npm -g install csv2md`, but my script did not recognise it. Then, I’ve install it locally; the script still did not recognise `csv2md`. When I used relative path (`csv2md = require('./node_modules/csv2md/src/csv2md')`, it works (`csv2md` contains `{ Csv2md: [Function: Csv2md], csv2md: [Function: csv2md] }`). So, why is not working without path being specified?

**Comment by inspiraller** [comment]
I think the creator has not exported anything from their index file. 

1. package.json main file = bin/csv2md

2. bin/csv2md
```
#!/usr/bin/env node
require('../src');
```
3. This defaults to src/index.js (generated from index.ts)
There is no module.exports in this file, so nothing is exported -hence its not working and cannot import.
index.ts - does not export anything.

For now I have created my own convertor. 

For you - just to note, it seems this package depends on - 'csv-parse'
You could also use this for now until this gets resolved.

**Install this package.**
```
npm i csv-parse
```
**code example** 
```
import parseCsv from 'csv-parse/lib/sync';
const arrCsrv = parseCsv('a,b,c'); // outputs [['a','b','c']] 
```
- see example tests - https://github.com/adaltas/node-csv-parse/blob/master/test/api.sync.coffee

With the array you can iterate over to generate your markdown table.

Hope it helps.

**Comment by pstaender** [comment]
Yes, @tukusejssirs @inspiraller the export / module api is unintended broken. I also did not realize the notification in the first place @tukusejssirs , so sry here for my late response.

The commit https://github.com/pstaender/csv2md/pull/14/commits/bb643a025ffbf32eeced65663dd006817cd11cb7 should fix this issue, for common js and module synntax:

```js
console.log(
  require('csv2md')
);

// or

import { Csv2md, csv2md } from 'csv2md';
console.log(
  {Csv2md, csv2md} 
)
```

`{ Csv2md: [Function: Csv2md], csv2md: [Function: csv2md] }`

I will publish a new version of the module later today (see pr)
