### ISSUE TITLE
Suggestion: Add options for selected columns and number format

### ISSUE THREAD

**Issue by rubyzhao** [pstaender/csv2md#9]
**This is very useful application. Would you please add the two options below?**

1. Only convert selected columns option: -c 1,2,4-6,8-10,15
This means it will covert column 1,2,4,5,6,8,9,10 and 15 only. 
2. Convert number only columns to string with number of decimals: -d 3
This will convert 123.45678 to 123.457

**Comment by pstaender** [comment]
Hi @rubyzhao , glad you like it :)

csv2md is just a format transformer, nor a filter nor a value converter. I think there are some tools out there to do that, e.g. https://github.com/jameswmoody/csv-filter-sort

**Comment by rubyzhao** [comment]
Hi @pstaender, thanks for your help to point it which will filters out some rows, not columns.
What I need is that only can convert a few selected columns with all rows in csv to markdown.

**Comment by pstaender** [comment]
Yes, I understand. But it should be done by another tool, no matter of column or row filtering. `csv2md` transforms just csv to markdown table, without filtering / changing any data. Maybe there is away to do that programmatically via transformer?

I hope you don't mind if I close that issue for now.

**Comment by h-g-s** [comment]
Hi, thanks for the great tool, my question is related, I would just like to know how to use the existing option  -r

-r 1   works

how do I specify more than one column ?

tried
-r "1,2: 
-r "1 2"
-r "1-2"

thank you very much

**Comment by pstaender** [comment]
Hi @h-g-s ,

I think you confuse this module with the python program https://pypi.org/project/csv2md/ (yeah, unfortunately both have the same name...). This module is written in JS, is more just a converter without filter abilities and therefore has other options:

```sh
$ csv2md -h
Converts CSV data to Markdown tables
(c) 2014-2020 by Philipp Staender, MIT License

Usage: csv2md [options] <csvfile>

Options:
  --version           Show version number                              [boolean]
  --pretty, -p        pretty output, i.e. optimized column width and not
                      inline-style                                     [boolean]
  --csvComment        ignore everything until next line after this character
  --tableDelimiter    delimiter for cells in output               [default: "|"]
  --cellPadding       chars / spaces to wrap cell content         [default: " "]
  --firstLineMarker   to seperate first row
                      you can specifiy own characters, for instance:
                      `-*` -> `------…` (gets cell width)
                      `-====-` -> `-====-`
                                                                 [default: "-*"]
  --delimiterOnBegin  first row delimiter                          [default: ""]
  --delimiterOnEnd    last row delimiter                           [default: ""]
  --parallel          number of transformation callbacks to run in parallel
                                                         [number] [default: 100]
  --csvDelimiter      column delimiter
  --csvQuote          cell quote
  --csvEscape         char to escape, see quoter
  -h, --help          Show help                                        [boolean]

Examples:
  csv2md -p data.csv > output.md          Converts csv to pretty markdown table
  cat data.csv | csv2md > output.md       Converts larger data
  csv2md --csvDelimiter=";" < ~/data.csv  Converts with a distinct csv delimiter
```
